import "./globals.css";

export const metadata = {
  title: "Movies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-zinc-800 text-zinc-300">{children}</body>
    </html>
  );
}
